# inspiration from https://github.com/Nemo157/roaring-rs/blob/master/.travis.yml
language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - (cargo install rustfmt || true)
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo install clippy --force;
    fi'
script:
  - export PATH=$PATH:~/.cargo/bin
  - cargo fmt -- --write-mode=diff
  - cargo build --features strict
  - cargo test --features strict
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo clippy -- -D warnings;
    fi'