language: rust
rust:
  - stable
  - beta
  - nightly
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script: (cargo install rustfmt || true)
script:
- |
  export PATH=$PATH:~/.cargo/bin &&
  cargo fmt -- --write-mode=diff &&
  cargo build --features strict &&
  cargo test --features strict